export const RECEIVE_TOKEN='receive_token'
export const RECEIVE_BLOG='receive_blog'
export const RECEIVE_STATE_TEXT='receive_state_text'
export const RECEIVE_ALL_CATEGORY='receive_all_category'
export const RECEIVE_ALL_ARTICALS='receive_all_articlas'
export const RECEIVE_ALL_REPORTS='receive_all_report'
export const RECEIVE_FIND_ARTICAL='receive_find_artical'
export const RECEIVE_COMPUTED_REPORTS='receive_computed_reports'
export const RECEIVE_COMPUTED_CATEGORY='receive_computed_categorys'
export const RECEIVE_COMPUTED_ARTICALS='receive_computed_articals'
export const RECEIVE_EDITOR_CATEGORY='receive_editor_category'
export const RECEIVE_SEARCH_REPORT='receive_search_report'

// export const RECEIVE_ADD_CATEGORY='receive_add_category'
// export const RECEIVE_DELETE_ARTICAL='receive_delete_artical'
// //export const RECEIVE_ADD_ARTICAL='receive_add_artical'
// export const RECEIVE_UPDATE_ARTICAL='receive_update_artical'
// export const RECEIVE_ADD_REPORT='receive_add_report'
// export const RECEIVE_DELETE_REPORT='receive_delete_report'
// export const RECEIVE_DELETE_CATEGORY='receive_delete_category'

