export const RECEIVE_TOKEN='receive_token'
export const RECEIVE_BLOG='receive_blog'
export const RECEIVE_STATES='receive_state'
export const RECEIVE_ALL_CATEGORY='receive_all_category'
export const RECEIVE_ALL_ARTICLAS='receive_all_articlas'
export const RECEIVE_ALL_REPORt='receive_all_report'
export const RECEIVE_ADD_CATEGORY='receive_add_category'
export const RECEIVE_DELETE_ARTICAL='receive_delete_artical'
//export const RECEIVE_ADD_ARTICAL='receive_add_artical'
export const RECEIVE_UPDATE_ARTICAL='receive_update_artical'
export const RECEIVE_ADD_REPORT='receive_add_report'
export const RECEIVE_DELETE_REPORT='receive_delete_report'
export const RECEIVE_DELETE_CATEGORY='receive_delete_category'

