export default{
    token:'',
    blog:null,
    allCategory:null,
    allArticals:null,
    allReports:{
        title:'文章专题',
        list:[{
            name:'',
            description:'',
        }]},
    stateText:'',
    findArtical:'',
    computedCategory:null,
    editorCategory:null,
    computedArticals:null,
    computedReports:{
        title:'文章专题',
        list:[{
            name:'',
            description:'',
        }]
    },
}